lanuage: ruby
rvm: 2.1.0
addons:
  postgresql: 9.3
services:
- postgresql
before_script:
- psql -c 'create database summaryapp_test;' -U postgres
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
- bundle exec rspec spec/
notifications:
  email:
    - ilya.blan4@gmail.com