default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: SummaryApp_development
  username: summaryapp
  password: summaryapp_pwd
  host: localhost
  port: 5432

test:
  <<: *default
  database: SummaryApp_test
  username: summaryapp
  password: summaryapp_pwd
  host: localhost
  port: 5432

production:
  <<: *default
  database: SummaryApp_production
  username: summaryapp
  password: <%= ENV['SUMMARYAPP_DATABASE_PASSWORD'] %>
