# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37330aef51b0686866c82b1ab76c2899ac3ad07ba62460a055d0a5142153ec4fc74c9ee530180e1d35c58591483946176b2be160d75c9173e3aa4c05bdf7a6e7

test:
  secret_key_base: b418f96c038f05ac5eae41ebea70fec7205d32c8dd8052d803cf88dac37b5cdc36e48d83b24dd23e5b28dc824abcecd1b73ff395afaed41ee75bc4987f82267a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %> 
