development:
  secret_key_base: '4f3764c3f7e363c0ff0076393eedd2c19ef50f143b3d525c2fd95c2bc24d6df9d0a5038a095580763165b3fa387448f6b0bfb89f5014e6bd8c2755fcbf3d891f'
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %> 

test:
  secret_key_base: '4f3764c3f7e363c0ff0076393eedd2c19ef50f143b3d525c2fd95c2bc24d6df9d0a5038a095580763165b3fa387448f6b0bfb89f5014e6bd8c2755fcbf3d891f'
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>  
 
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  mongohq_uri: <%= ENV['MONGOHQ_URI'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %> 